# data.py

quiz_data = [
    {"question": "A slug’s blood is green.", "answer": "True"},
    {"question": "The Great Wall of China is visible from space.", "answer": "False"},
    {"question": "Sharks are mammals.", "answer": "False"},
    {"question": "An octopus has three hearts.", "answer": "True"},
    {"question": "The Sun is a planet.", "answer": "False"},
    {"question": "The human body has 206 bones.", "answer": "True"},
    {"question": "Venus is the hottest planet in our solar system.", "answer": "True"},
    {"question": "Bats are blind.", "answer": "False"},
    {"question": "Lightning never strikes in the same place twice.", "answer": "False"},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"question": "Bees can recognize human faces.", "answer": "True"},
    {"question": "Humans and bananas share about 60% of the same DNA.", "answer": "True"},
    {"question": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"question": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"question": "Penguins can fly.", "answer": "False"},
    {"question": "The Earth revolves around the Moon.", "answer": "False"},
    {"question": "The blue whale is the largest animal ever known to have existed.", "answer": "True"},
    {"question": "Your fingernails keep growing after you die.", "answer": "False"},
    {"question": "Water boils at 100 degrees Celsius.", "answer": "True"},
    {"question": "Humans have more than five senses.", "answer": "True"},
    {"question": "Camels store water in their humps.", "answer": "False"},
    {"question": "Jupiter is smaller than Earth.", "answer": "False"},
    {"question": "Butterflies taste with their feet.", "answer": "True"},
    {"question": "Some cats are allergic to humans.", "answer": "True"},
    {"question": "Your brain stops growing after age 10.", "answer": "False"},
    {"question": "The total surface area of a human’s lungs is the size of a tennis court.", "answer": "True"},
    {"question": "There are seven continents on Earth.", "answer": "True"},
    {"question": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"question": "The loudest animal is the African Elephant.", "answer": "False"},
    {"question": "The Milky Way is a galaxy.", "answer": "True"},
    {"question": "Lightning is hotter than the surface of the Sun.", "answer": "True"},
    {"question": "The Eiffel Tower is located in London.", "answer": "False"},
    {"question": "Albert Einstein developed the theory of relativity.", "answer": "True"},
    {"question": "Venus rotates in the opposite direction to most other planets.", "answer": "True"},
    {"question": "There are more bones in a baby than in an adult.", "answer": "True"},
    {"question": "Your tongue is the strongest muscle in your body.", "answer": "False"},
    {"question": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"question": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"question": "The first man to walk on the moon was Neil Armstrong.", "answer": "True"},
    {"question": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"question": "Owls can rotate their heads almost 360 degrees.", "answer": "True"},
    {"question": "Sound travels faster in air than in water.", "answer": "False"},
    {"question": "The capital of Australia is Sydney.", "answer": "False"},
    {"question": "There are 24 hours in a day because Earth rotates once on its axis in that time.", "answer": "True"},
    {"question": "Your heart is located on the right side of your chest.", "answer": "False"},
    {"question": "Humans have walked on Mars.", "answer": "False"},
    {"question": "Bananas grow on trees.", "answer": "False"},
    {"question": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"question": "Octopuses can change the color of their skin.", "answer": "True"},
    {"question": "The freezing point of water is 0 degrees Celsius.", "answer": "True"},
    {"question": "The brain is the largest organ in the human body.", "answer": "False"}
]